var annotated_dup =
[
    [ "Admin", "da/ddc/class_admin.html", "da/ddc/class_admin" ],
    [ "AlreadyInteracted", "d9/d69/class_already_interacted.html", null ],
    [ "AlreadyStreaming", "da/d02/class_already_streaming.html", null ],
    [ "AlreadyViewing", "d5/d3a/class_already_viewing.html", null ],
    [ "Date", "d4/d53/struct_date.html", "d4/d53/struct_date" ],
    [ "FullCapacity", "d5/d52/class_full_capacity.html", null ],
    [ "HasNotInteracted", "d8/d55/class_has_not_interacted.html", null ],
    [ "InactiveUser", "d8/d05/class_inactive_user.html", null ],
    [ "InvalidDate", "d8/d64/class_invalid_date.html", "d8/d64/class_invalid_date" ],
    [ "InvalidFile", "d2/d8d/class_invalid_file.html", "d2/d8d/class_invalid_file" ],
    [ "InvalidLanguage", "d2/df2/class_invalid_language.html", "d2/df2/class_invalid_language" ],
    [ "Menu", "d2/db8/class_menu.html", "d2/db8/class_menu" ],
    [ "NameAlreadyInUse", "d4/df0/class_name_already_in_use.html", null ],
    [ "NoMinimumAge", "d3/d04/class_no_minimum_age.html", null ],
    [ "NotInPrivateStream", "de/de3/class_not_in_private_stream.html", null ],
    [ "PrivateStream", "df/d6f/class_private_stream.html", "df/d6f/class_private_stream" ],
    [ "PublicStream", "d3/d3f/class_public_stream.html", "d3/d3f/class_public_stream" ],
    [ "Stream", "d1/d51/class_stream.html", "d1/d51/class_stream" ],
    [ "Streamer", "d7/dca/class_streamer.html", "d7/dca/class_streamer" ],
    [ "StreamZ", "d5/d41/class_stream_z.html", "d5/d41/class_stream_z" ],
    [ "UnauthorizedViewer", "d9/d8c/class_unauthorized_viewer.html", null ],
    [ "User", "d7/d23/class_user.html", "d7/d23/class_user" ],
    [ "Viewer", "d0/d30/class_viewer.html", "d0/d30/class_viewer" ]
];